# Generated by Django 3.2.6 on 2022-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.IntegerField(default=None, max_length=128, null=True),
        ),
    ]
