# Generated by Django 3.2.6 on 2022-06-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20220607_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user_id',
            new_name='user',
        ),
    ]
